---
- name: "Setup locales"
  community.general.locale_gen:
    name: "{{ item }}"
    state: present
  with_items:
    "{{locales}}"

- name: "Set timezone to {{timezone_name}}"
  timezone:
    name: "{{timezone_name}}"

- name: "Add sources.list"
  template:
    src: "etc/apt/sources.list.j2"
    dest: "/etc/apt/sources.list"
    mode: 0644
  notify: update_apt_cache

- name: "Install basic packages"
  apt:
    update_cache: true
    name:
      '{{ packages }}'

- name: Create sysctl configuration
  template:
    src: "etc/sysctl.conf.j2"
    dest: "{{ sysctl_config_location }}"
  notify:
    - Reload sysctl configuration

- name: Create ulimit configuration
  template:
    src: "etc/security/limits.conf.j2"
    dest: "{{ ulimit_config_location }}"

- name: Change the hostname to our standard
  hostname:
    name="{{ inventory_hostname }}"
  when:
    ansible_fqdn != ansible_ssh_host

- name: Added hostname configuration to /etc/hosts
  lineinfile:
    state=present
    dest=/etc/hosts
    line="{{ ansible_default_ipv4.address }} {{ inventory_hostname }} {{ ansible_hostname }}"
    regexp="^{{ ansible_default_ipv4.address }}"
  when:
    ansible_fqdn != inventory_hostname

- name: Validate hostname configuration
  assert:
    that:
      ansible_fqdn == inventory_hostname
